AGENT_PER_ENV = 200

CONFIG_DIR = "configs"
SIMULATION_CONFIG = "simulation_config.yml"
MODEL_CONFIG = "model_configs.json"
MEMORY_CONFIG = "memory_config.json"

INSTRUCTION_BEGIN = "[INSTRUCTION]\n"
INSTRUCTION_END = "\n[\INSTRUCTION]\n"
PROFILE_BEGIN = "[PROFILE]\n"
PROFILE_END = "\n[\PROFILE]\n"
MEMORY_BEGIN = "[MEMORY]\n"
MEMORY_END = "\n[\MEMORY]\n"
INTERVENTION_BEGIN = "[INTERVENTION]\n"
INTERVENTION_END = "\n[\INTERVENTION]\n"